//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentACar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezervasyon
    {
        public string RezId { get; set; }
        public System.DateTime RezTarih { get; set; }
        public System.DateTime RezBaslangic { get; set; }
        public System.DateTime RezBitis { get; set; }
        public string RezAracId { get; set; }
        public string RezMusteriId { get; set; }
        public int RezIslemYapan { get; set; }
        public int RezGunSayisi { get; set; }
        public decimal RezTutar { get; set; }
    
        public virtual Araclar Araclar { get; set; }
        public virtual Musteri Musteri { get; set; }
        public virtual Uyeler Uyeler { get; set; }
    }
}
